/* ==========================================================================
   LogSense demo — i18n: English / Hindi / Marathi.
   dict entries are [en, hi, mr]. LS.t(key) picks by the current language,
   falling back to English. Raw maintenance log text is never translated —
   it is the authentic source data the product reads.
   ========================================================================== */

window.LS = window.LS || {};

(function () {
  "use strict";

  const LANG_KEY = "logsense-lang";
  const ORDER = { en: 0, hi: 1, mr: 2 };

  let lang = "en";
  try { lang = sessionStorage.getItem(LANG_KEY) || "en"; } catch (e) { /* noop */ }
  if (!(lang in ORDER)) lang = "en";

  const dict = {
    /* ---- navigation ---- */
    "nav.dashboard": ["Dashboard", "डैशबोर्ड", "डॅशबोर्ड"],
    "nav.machines": ["Machines", "मशीनें", "मशीन्स"],
    "nav.history": ["Maintenance History", "मेंटेनेंस इतिहास", "मेंटेनन्स इतिहास"],
    "nav.patterns": ["Patterns & Insights", "पैटर्न और इनसाइट", "पॅटर्न आणि इनसाइट"],
    "nav.parts": ["Spare Parts", "स्पेयर पार्ट्स", "स्पेअर पार्ट्स"],
    "nav.assistant": ["Maintenance Assistant", "मेंटेनेंस असिस्टेंट", "मेंटेनन्स असिस्टंट"],
    "nav.whatsapp": ["WhatsApp Agent", "व्हाट्सऐप एजेंट", "व्हॉट्सॲप एजंट"],
    "nav.upload": ["Upload & Import", "अपलोड और इम्पोर्ट", "अपलोड आणि इम्पोर्ट"],
    "nav.validation": ["Validation Queue", "जाँच कतार", "तपासणी रांग"],
    "nav.users": ["Users & Roles", "उपयोगकर्ता और भूमिकाएँ", "वापरकर्ते आणि भूमिका"],
    "nav.settings": ["Settings", "सेटिंग्स", "सेटिंग्ज"],
    "nav.how": ["How It Works", "यह कैसे काम करता है", "हे कसे काम करते"],
    "nav.closing": ["Closing Slide", "समापन स्लाइड", "समारोप स्लाईड"],
    "grp.operations": ["Operations", "संचालन", "ऑपरेशन्स"],
    "grp.ai": ["AI", "एआई", "एआय"],
    "grp.data": ["Data", "डेटा", "डेटा"],
    "grp.admin": ["Administration", "प्रशासन", "प्रशासन"],
    "grp.demo": ["Demo", "डेमो", "डेमो"],

    /* ---- chrome ---- */
    "chrome.demoEnv": ["Demo Environment", "डेमो एनवायरनमेंट", "डेमो एन्व्हायर्नमेंट"],
    "chrome.searchPh": ["Search machines, records, parts… (try “brng” or 6205ZZ)", "मशीन, रिकॉर्ड, पार्ट खोजें… (जैसे “brng” या 6205ZZ)", "मशीन, रेकॉर्ड, पार्ट शोधा… (उदा. “brng” किंवा 6205ZZ)"],
    "role.manager": ["Maintenance Manager", "मेंटेनेंस मैनेजर", "मेंटेनन्स मॅनेजर"],

    /* ---- login ---- */
    "login.signin": ["Sign in", "साइन इन", "साइन इन"],
    "login.sub": ["Enterprise access for your plant team.", "आपकी प्लांट टीम के लिए एंटरप्राइज़ एक्सेस।", "तुमच्या प्लांट टीमसाठी एंटरप्राइझ ॲक्सेस."],
    "login.demoBtn": ["Demo login — Maintenance Manager", "डेमो लॉगिन — मेंटेनेंस मैनेजर", "डेमो लॉगिन — मेंटेनन्स मॅनेजर"],
    "login.tagline": ["Turn years of maintenance history into searchable intelligence.", "सालों का मेंटेनेंस इतिहास — अब खोजने लायक़ इंटेलिजेंस।", "वर्षानुवर्षांचा मेंटेनन्स इतिहास — आता शोधण्याजोगी इंटेलिजन्स."],

    /* ---- badges & statuses ---- */
    "badge.FACT": ["FACT", "तथ्य", "तथ्य"],
    "badge.CALCULATED": ["CALCULATED", "गणना", "गणना"],
    "badge.HYPOTHESIS": ["HYPOTHESIS", "अनुमान", "अंदाज"],
    "badge.NEW": ["NEW", "नया", "नवीन"],
    "badge.REVIEW": ["REVIEW", "जाँच", "तपासणी"],
    "badge.FACT.tip": ["Directly supported by maintenance records.", "सीधे मेंटेनेंस रिकॉर्ड पर आधारित।", "थेट मेंटेनन्स रेकॉर्डवर आधारित."],
    "badge.CALCULATED.tip": ["Computed deterministically from structured maintenance records — not generated by the AI.", "स्ट्रक्चर्ड रिकॉर्ड से गणना — AI नंबर नहीं बनाता।", "स्ट्रक्चर्ड रेकॉर्डवरून गणना — AI आकडे तयार करत नाही."],
    "badge.HYPOTHESIS.tip": ["Possible explanation. Requires human engineering validation — never shown as a confirmed root cause.", "संभावित कारण। इंजीनियरिंग जाँच ज़रूरी — इसे पक्का कारण नहीं माना जाता।", "संभाव्य कारण. इंजिनिअरिंग तपासणी आवश्यक — निश्चित कारण मानले जात नाही."],
    "badge.NEW.tip": ["Added in this session.", "इसी सेशन में जोड़ा गया।", "याच सेशनमध्ये जोडले."],
    "badge.REVIEW.tip": ["Requires engineering review.", "इंजीनियरिंग जाँच ज़रूरी।", "इंजिनिअरिंग तपासणी आवश्यक."],
    "status.Healthy": ["Healthy", "ठीक है", "सुस्थितीत"],
    "status.Attention": ["Attention", "ध्यान दें", "लक्ष द्या"],
    "status.Recurring": ["Recurring", "बार-बार खराबी", "वारंवार बिघाड"],

    /* ---- common labels ---- */
    "lbl.machine": ["Machine", "मशीन", "मशीन"],
    "lbl.line": ["Line", "लाइन", "लाईन"],
    "lbl.type": ["Type", "प्रकार", "प्रकार"],
    "lbl.records": ["Records", "रिकॉर्ड", "रेकॉर्ड"],
    "lbl.downtime": ["Downtime", "डाउनटाइम", "डाउनटाइम"],
    "lbl.downtimeHrs": ["Downtime (hrs)", "डाउनटाइम (घंटे)", "डाउनटाइम (तास)"],
    "lbl.lastEvent": ["Last event", "आख़िरी घटना", "शेवटची घटना"],
    "lbl.status": ["Status", "स्थिति", "स्थिती"],
    "lbl.date": ["Date", "तारीख", "तारीख"],
    "lbl.failureMode": ["Failure mode", "खराबी का प्रकार", "बिघाडाचा प्रकार"],
    "lbl.originalEntry": ["Original entry", "मूल एंट्री", "मूळ नोंद"],
    "lbl.source": ["Source", "स्रोत", "स्रोत"],
    "lbl.action": ["Action", "काम", "कृती"],
    "lbl.part": ["Part", "पार्ट", "पार्ट"],
    "lbl.technician": ["Technician", "तकनीशियन", "तंत्रज्ञ"],
    "lbl.usage": ["Usage", "उपयोग", "वापर"],
    "lbl.lastUsed": ["Last used", "आख़िरी उपयोग", "शेवटचा वापर"],
    "lbl.trend": ["Trend", "ट्रेंड", "ट्रेंड"],
    "lbl.breakdown": ["Breakdown", "ब्रेकडाउन", "ब्रेकडाउन"],
    "unit.hrs": ["hrs", "घंटे", "तास"],
    "lbl.today": ["Today", "आज", "आज"],
    "drawer.title": ["Source Record", "स्रोत रिकॉर्ड", "स्रोत रेकॉर्ड"],
    "drawer.original": ["Original entry (as recorded)", "मूल एंट्री (जैसी लिखी गई)", "मूळ नोंद (जशी लिहिली)"],
    "drawer.normalized": ["Normalized interpretation", "साफ़ किया गया रूप", "नॉर्मलाइझ केलेले रूप"],
    "lbl.sheet": ["Sheet / section", "शीट / भाग", "शीट / विभाग"],
    "lbl.row": ["Row / page", "पंक्ति / पेज", "ओळ / पान"],
    "lbl.recordId": ["Record ID", "रिकॉर्ड ID", "रेकॉर्ड ID"],
    "drawer.open": ["Open", "खोलें", "उघडा"],

    /* ---- buttons ---- */
    "btn.viewSource": ["View source", "स्रोत देखें", "स्रोत पहा"],
    "btn.approve": ["Approve", "मंज़ूर करें", "मंजूर करा"],
    "btn.edit": ["Edit", "बदलें", "बदला"],
    "btn.reject": ["Reject", "अस्वीकार", "नाकारा"],
    "btn.confirm": ["Confirm", "पुष्टि करें", "निश्चित करा"],
    "btn.viewEvidence": ["View evidence", "सबूत देखें", "पुरावा पहा"],
    "btn.viewHistory": ["View history", "इतिहास देखें", "इतिहास पहा"],
    "btn.viewPartUsage": ["View part usage", "पार्ट उपयोग देखें", "पार्ट वापर पहा"],
    "btn.askAi": ["Ask AI about this machine", "इस मशीन के बारे में AI से पूछें", "या मशीनबद्दल AI ला विचारा"],
    "btn.findSimilar": ["Find similar failures", "मिलती-जुलती खराबियाँ खोजें", "सारखे बिघाड शोधा"],
    "btn.uploadData": ["Upload historical data", "पुराना डेटा अपलोड करें", "जुना डेटा अपलोड करा"],
    "btn.howItWorks": ["How it works", "यह कैसे काम करता है", "हे कसे काम करते"],
    "btn.allPatterns": ["All patterns", "सभी पैटर्न", "सर्व पॅटर्न"],
    "btn.reviewRecords": ["Review records", "रिकॉर्ड जाँचें", "रेकॉर्ड तपासा"],
    "btn.backToDash": ["Back to dashboard", "डैशबोर्ड पर वापस", "डॅशबोर्डकडे परत"],
    "btn.details": ["Details", "विवरण", "तपशील"],

    /* ---- dashboard ---- */
    "dash.title": ["Plant Maintenance Intelligence", "प्लांट मेंटेनेंस इंटेलिजेंस", "प्लांट मेंटेनन्स इंटेलिजन्स"],
    "dash.period": ["Last 12 months", "पिछले 12 महीने", "गेले 12 महिने"],
    "dash.demoNote": ["demo dataset — not real customer data", "डेमो डेटा — असली ग्राहक डेटा नहीं", "डेमो डेटा — खरा ग्राहक डेटा नाही"],
    "dash.kpi.breakdowns": ["Breakdown events", "ब्रेकडाउन घटनाएँ", "ब्रेकडाउन घटना"],
    "dash.kpi.indexed": ["Records indexed", "रिकॉर्ड इंडेक्स हुए", "रेकॉर्ड इंडेक्स झाले"],
    "dash.kpi.pending": ["Validation pending", "जाँच बाकी", "तपासणी बाकी"],
    "dash.kpi.pendingFoot": ["Below auto-approval confidence", "ऑटो-मंज़ूरी सीमा से नीचे", "ऑटो-मंजुरी मर्यादेखाली"],
    "dash.vsPrev": ["vs previous period", "पिछली अवधि से", "मागील कालावधीशी"],
    "dash.insights": ["AI-detected maintenance insights", "AI द्वारा पकड़े गए मेंटेनेंस इनसाइट", "AI ने शोधलेले मेंटेनन्स इनसाइट"],
    "dash.trendTitle": ["Downtime trend", "डाउनटाइम ट्रेंड", "डाउनटाइम ट्रेंड"],
    "dash.topTitle": ["Top machines by downtime", "सबसे ज़्यादा डाउनटाइम वाली मशीनें", "सर्वाधिक डाउनटाइम असलेल्या मशीन्स"],
    "dash.paretoTitle": ["Failure mode Pareto", "खराबी के प्रकार (परेटो)", "बिघाड प्रकार (परेटो)"],
    "dash.sourcesTitle": ["Where the data comes from", "डेटा कहाँ से आता है", "डेटा कुठून येतो"],
    "dash.sourcesNote": ["no sensors · no SAP migration", "न सेंसर · न SAP बदलाव", "सेन्सर नाही · SAP बदल नाही"],
    "ins.recurBearing": ["Recurring bearing failure", "बार-बार बेयरिंग खराबी", "वारंवार बेअरिंग बिघाड"],
    "ins.recurTitle": ["Possible ~{d}-day bearing recurrence", "बेयरिंग खराबी ~{d} दिन में दोहराव संभव", "बेअरिंग बिघाड ~{d} दिवसांनी पुनरावृत्ती शक्य"],
    "ins.recurBody": ["<b>{n} bearing replacements</b> in {m} months{today}. Alignment was checked after each replacement, yet the failure returned. Possible mounting/alignment issue — requires engineering validation.", "{m} महीनों में <b>{n} बार बेयरिंग बदली</b>{today}। हर बार अलाइनमेंट जाँची गई, फिर भी खराबी लौट आई। माउंटिंग/अलाइनमेंट की समस्या हो सकती है — इंजीनियरिंग जाँच ज़रूरी।", "{m} महिन्यांत <b>{n} वेळा बेअरिंग बदलले</b>{today}. दरवेळी अलाइनमेंट तपासले, तरी बिघाड परत आला. माउंटिंग/अलाइनमेंटचा प्रश्न असू शकतो — इंजिनिअरिंग तपासणी आवश्यक."],
    "ins.recurToday": [" — including today’s record", " — आज का रिकॉर्ड भी शामिल", " — आजचे रेकॉर्डही समाविष्ट"],
    "ins.sensor": ["Repeated sensor failure", "बार-बार सेंसर खराबी", "वारंवार सेन्सर बिघाड"],
    "ins.sensorTitle": ["Temporary fix followed by recurrence", "अस्थायी मरम्मत के बाद फिर खराबी", "तात्पुरत्या दुरुस्तीनंतर पुन्हा बिघाड"],
    "ins.sensorBody": ["<b>{n} sensor-related stoppages</b> since {from}. Cleaning was done twice; the machine stopped again each time until the proximity sensor was replaced.", "{from} से <b>{n} बार सेंसर की वजह से मशीन रुकी</b>। दो बार सफाई की गई; हर बार मशीन फिर रुकी — आख़िर में सेंसर बदलना पड़ा।", "{from} पासून <b>{n} वेळा सेन्सरमुळे मशीन थांबली</b>. दोनदा सफाई केली; दरवेळी मशीन पुन्हा थांबली — शेवटी सेन्सर बदलावा लागला."],
    "ins.part": ["Spare part concentration", "स्पेयर पार्ट का केंद्रित उपयोग", "स्पेअर पार्टचा एकवटलेला वापर"],
    "ins.partTitle": ["6205ZZ bearing consumption", "6205ZZ बेयरिंग की खपत", "6205ZZ बेअरिंगचा वापर"],
    "ins.partBody": ["Used across <b>{m} machines</b> ({n} recorded replacements). Line 3 accounts for <b>{p}%</b> of recorded consumption.", "<b>{m} मशीनों</b> में इस्तेमाल ({n} बार बदली गई)। कुल खपत का <b>{p}%</b> Line 3 पर।", "<b>{m} मशीन्समध्ये</b> वापर ({n} वेळा बदलले). एकूण वापरापैकी <b>{p}%</b> Line 3 वर."],
    "ins.evidence": ["evidence records", "सबूत रिकॉर्ड", "पुरावा रेकॉर्ड"],

    /* ---- machines / history ---- */
    "machines.title": ["Machine Master", "मशीन मास्टर", "मशीन मास्टर"],
    "machines.sub": ["Every machine LogSense resolved from your historical records — aliases, shorthand and all.", "आपके पुराने रिकॉर्ड से LogSense ने पहचानी हर मशीन — छोटे नाम और शॉर्टहैंड समेत।", "तुमच्या जुन्या रेकॉर्डमधून LogSense ने ओळखलेली प्रत्येक मशीन — टोपणनावे आणि शॉर्टहँडसह."],
    "machines.searchPh": ["Search machines, IDs, aliases…", "मशीन, ID, नाम खोजें…", "मशीन, ID, नाव शोधा…"],
    "machines.allLines": ["All lines", "सभी लाइनें", "सर्व लाईन्स"],
    "machines.allStatuses": ["All statuses", "सभी स्थितियाँ", "सर्व स्थिती"],
    "history.title": ["Maintenance History", "मेंटेनेंस इतिहास", "मेंटेनन्स इतिहास"],
    "history.sub": ["Normalized records from every source. Search understands technician shorthand and Hinglish — try “bearing gaya” or “brng noise conveyor”.", "हर स्रोत से साफ़ किए गए रिकॉर्ड। खोज शॉर्टहैंड और हिंग्लिश समझती है — “bearing gaya” या “brng noise” आज़माएँ।", "प्रत्येक स्रोतातील नॉर्मलाइझ केलेले रेकॉर्ड. शोध शॉर्टहँड आणि हिंग्लिश समजतो — “bearing gaya” किंवा “brng noise” करून पहा."],
    "md.timeline": ["Maintenance timeline", "मेंटेनेंस टाइमलाइन", "मेंटेनन्स टाइमलाइन"],
    "md.newestFirst": ["records · newest first", "रिकॉर्ड · नए पहले", "रेकॉर्ड · नवीन आधी"],
    "md.pattern": ["Detected pattern", "मिला हुआ पैटर्न", "आढळलेला पॅटर्न"],
    "md.stat.mttrFoot": ["avg repair time (breakdowns)", "औसत मरम्मत समय", "सरासरी दुरुस्ती वेळ"],
    "md.stat.mtbfFoot": ["between breakdowns, observed window", "दो ब्रेकडाउन के बीच का औसत", "दोन ब्रेकडाउनमधील सरासरी"],
    "md.stat.breakdowns": ["Breakdowns", "ब्रेकडाउन", "ब्रेकडाउन"],
    "md.stat.breakdownsFoot": ["in record history", "रिकॉर्ड इतिहास में", "रेकॉर्ड इतिहासात"],
    "md.stat.totalDt": ["Total downtime", "कुल डाउनटाइम", "एकूण डाउनटाइम"],
    "md.stat.totalDtFoot": ["sum of recorded downtime", "दर्ज डाउनटाइम का जोड़", "नोंदवलेल्या डाउनटाइमची बेरीज"],
    "md.stat.lastFailure": ["Last failure", "आख़िरी खराबी", "शेवटचा बिघाड"],
    "md.stat.repeat": ["Repeat failures", "दोहराई खराबियाँ", "पुनरावृत्त बिघाड"],
    "md.stat.repeatFoot": ["events in modes seen ≥2×", "जो खराबी ≥2 बार दिखी", "≥2 वेळा दिसलेले बिघाड"],
    "md.recurTitle": ["Recurrence alert — {n}th bearing replacement in {m} months", "अलर्ट — {m} महीनों में {n}वीं बार बेयरिंग बदली", "अलर्ट — {m} महिन्यांत {n}वे बेअरिंग बदल"],
    "md.recurBody": ["Today’s record #2048 is the {n}th bearing replacement on this motor (previous interval ~{d} days). Status: <b>Requires engineering review</b> — LogSense flags the pattern; it does not confirm a root cause.", "आज का रिकॉर्ड #2048 इस मोटर पर {n}वीं बेयरिंग बदली है (पिछला अंतराल ~{d} दिन)। स्थिति: <b>इंजीनियरिंग जाँच ज़रूरी</b> — LogSense पैटर्न दिखाता है, पक्का कारण नहीं बताता।", "आजचे रेकॉर्ड #2048 — या मोटरवरील {n}वे बेअरिंग बदल (मागील अंतर ~{d} दिवस). स्थिती: <b>इंजिनिअरिंग तपासणी आवश्यक</b> — LogSense पॅटर्न दाखवते, निश्चित कारण सांगत नाही."],
    "md.patternBody": ["<b>{n} bearing replacements</b> between {from} and {to} — average interval <b>~{d} days</b>.", "{from} से {to} के बीच <b>{n} बार बेयरिंग बदली</b> — औसत अंतराल <b>~{d} दिन</b>।", "{from} ते {to} दरम्यान <b>{n} वेळा बेअरिंग बदलले</b> — सरासरी अंतर <b>~{d} दिवस</b>."],

    /* ---- assistant ---- */
    "ai.hero": ["Maintenance Intelligence", "मेंटेनेंस इंटेलिजेंस", "मेंटेनन्स इंटेलिजन्स"],
    "ai.heroSub": ["Ask questions about your plant’s maintenance history — in English, Hindi or Hinglish. Every answer links back to the source records.", "अपने प्लांट के मेंटेनेंस इतिहास के बारे में पूछें — हिंदी, मराठी या अंग्रेज़ी में। हर जवाब असली रिकॉर्ड से जुड़ा है।", "तुमच्या प्लांटच्या मेंटेनन्स इतिहासाबद्दल विचारा — मराठी, हिंदी किंवा इंग्रजीत. प्रत्येक उत्तर मूळ रेकॉर्डशी जोडलेले आहे."],
    "ai.inputPh": ["Ask about machines, failures, downtime, spare parts…", "मशीन, खराबी, डाउनटाइम, पार्ट के बारे में पूछें…", "मशीन, बिघाड, डाउनटाइम, पार्टबद्दल विचारा…"],
    "ai.ask": ["Ask", "पूछें", "विचारा"],
    "ai.summary": ["Summary", "सारांश", "सारांश"],
    "ai.keyFailures": ["Key failures", "मुख्य खराबियाँ", "मुख्य बिघाड"],
    "ai.stats": ["Statistics", "आँकड़े", "आकडेवारी"],
    "ai.patterns": ["Patterns", "पैटर्न", "पॅटर्न"],
    "ai.sources": ["Sources", "स्रोत", "स्रोत"],
    "ai.answer": ["Answer", "जवाब", "उत्तर"],
    "ai.possible": ["Possible", "संभावित", "संभाव्य"],
    "ai.calcNote": ["Calculated from maintenance records", "मेंटेनेंस रिकॉर्ड से गणना", "मेंटेनन्स रेकॉर्डवरून गणना"],
    "ai.calcStat": ["Calculated statistic", "गणना किया गया आँकड़ा", "गणना केलेली आकडेवारी"],
    "ai.totalDt": ["Total downtime", "कुल डाउनटाइम", "एकूण डाउनटाइम"],
    "ai.breakdownEvents": ["Breakdown events", "ब्रेकडाउन घटनाएँ", "ब्रेकडाउन घटना"],
    "ai.avgRepair": ["Avg repair time", "औसत मरम्मत समय", "सरासरी दुरुस्ती वेळ"],
    "ai.incidents": ["{n} incident(s)", "{n} बार", "{n} वेळा"],
    "ai.summaryMachine": ["<b>{name}</b> has <b>{n} maintenance records</b> between {from} and {to} — {b} breakdowns plus preventive and inspection entries.", "<b>{name}</b> पर {from} से {to} के बीच <b>{n} मेंटेनेंस रिकॉर्ड</b> हैं — {b} ब्रेकडाउन, साथ में PM और निरीक्षण एंट्री।", "<b>{name}</b> वर {from} ते {to} दरम्यान <b>{n} मेंटेनन्स रेकॉर्ड</b> आहेत — {b} ब्रेकडाउन, तसेच PM आणि तपासणी नोंदी."],
    "ai.pattern92": ["A bearing-related recurrence appears approximately every <b>{d} days</b> — {n} bearing replacements between {from} and {to}.", "बेयरिंग खराबी लगभग हर <b>{d} दिन</b> में दोहराई जा रही है — {from} से {to} के बीच {n} बार बेयरिंग बदली गई।", "बेअरिंग बिघाड साधारण दर <b>{d} दिवसांनी</b> पुन्हा होत आहे — {from} ते {to} दरम्यान {n} वेळा बेअरिंग बदलले."],
    "ai.hypoBearing": ["Repeated bearing replacement despite alignment checks may indicate a mounting/alignment issue on this motor.", "अलाइनमेंट जाँच के बावजूद बार-बार बेयरिंग बदलनी पड़ रही है — इस मोटर में माउंटिंग/अलाइनमेंट की समस्या हो सकती है।", "अलाइनमेंट तपासूनही वारंवार बेअरिंग बदलावे लागते — या मोटरमध्ये माउंटिंग/अलाइनमेंटचा प्रश्न असू शकतो."],
    "ai.hypoDisclaimer": ["This is a hypothesis and requires engineering validation — it is never promoted to a confirmed root cause automatically.", "यह सिर्फ़ एक अनुमान है — इंजीनियरिंग जाँच ज़रूरी है। इसे अपने-आप पक्का कारण नहीं माना जाता।", "हा फक्त अंदाज आहे — इंजिनिअरिंग तपासणी आवश्यक. हे आपोआप निश्चित कारण मानले जात नाही."],
    "ai.calcTip": ["Statistics are calculated from structured maintenance records — the AI does not invent KPI values.", "आँकड़े स्ट्रक्चर्ड मेंटेनेंस रिकॉर्ड से गणना होते हैं — AI नंबर नहीं बनाता।", "आकडेवारी स्ट्रक्चर्ड मेंटेनन्स रेकॉर्डवरून मोजली जाते — AI आकडे तयार करत नाही."],
    "ai.recordsIncluded": ["{a} records included · {b}/{a} had valid downtime", "{a} रिकॉर्ड शामिल · {b}/{a} में डाउनटाइम दर्ज था", "{a} रेकॉर्ड समाविष्ट · {b}/{a} मध्ये डाउनटाइम नोंद होती"],
    "ai.breakdownsIncluded": ["{n} breakdown records included · all had recorded downtime", "{n} ब्रेकडाउन रिकॉर्ड शामिल · सभी में डाउनटाइम दर्ज था", "{n} ब्रेकडाउन रेकॉर्ड समाविष्ट · सर्वांत डाउनटाइम नोंद होती"],
    "ai.matching": ["Matching records", "मिलते-जुलते रिकॉर्ड", "जुळणारे रेकॉर्ड"],
    "ai.whyMatched": ["Why this matched:", "यह क्यों मैच हुआ:", "हे का जुळले:"],
    "ai.byMachine": ["Breakdown by machine", "मशीन के हिसाब से", "मशीननुसार"],
    "ai.machinesUsing": ["Machines using this part", "यह पार्ट इस्तेमाल करने वाली मशीनें", "हा पार्ट वापरणाऱ्या मशीन्स"],
    "ai.similar": ["Similar failures across the plant", "प्लांट में मिलती-जुलती खराबियाँ", "प्लांटमधील सारखे बिघाड"],
    "ai.top5": ["Top 5 by downtime", "डाउनटाइम में टॉप 5", "डाउनटाइममध्ये टॉप 5"],
    "ai.fallbackTitle": ["I can help with your maintenance history", "मैं आपके मेंटेनेंस इतिहास में मदद कर सकता हूँ", "मी तुमच्या मेंटेनन्स इतिहासात मदत करू शकतो"],
    "ai.fallbackBody": ["In this demo I can answer questions about <b>machines, failures, downtime, spare parts and maintenance history</b>. Try one of these:", "इस डेमो में मैं <b>मशीन, खराबी, डाउनटाइम, स्पेयर पार्ट और मेंटेनेंस इतिहास</b> के सवालों के जवाब दे सकता हूँ। ये आज़माएँ:", "या डेमोमध्ये मी <b>मशीन, बिघाड, डाउनटाइम, स्पेअर पार्ट आणि मेंटेनन्स इतिहास</b> याबद्दल उत्तरे देऊ शकतो. हे करून पहा:"],
    "ai.repeatSummary": ["<b>{n} machines</b> have repeated (≥2) bearing failures in the recorded history.", "<b>{n} मशीनों</b> में 2 या ज़्यादा बार बेयरिंग खराब हुई है।", "<b>{n} मशीनमध्ये</b> 2 किंवा जास्त वेळा बेअरिंग खराब झाले आहे."],
    "ai.repeatHeader": ["Machines with repeated bearing failures", "बार-बार बेयरिंग खराबी वाली मशीनें", "वारंवार बेअरिंग बिघाड असलेल्या मशीन्स"],
    "ai.repeatItem": ["{n} bearing replacements, {h} hrs downtime", "{n} बार बेयरिंग बदली, {h} घंटे डाउनटाइम", "{n} वेळा बेअरिंग बदलले, {h} तास डाउनटाइम"],
    "ai.moreSingle": ["{n} more machine(s) had a single bearing event.", "{n} और मशीन में एक बार बेयरिंग खराब हुई।", "आणखी {n} मशीनमध्ये एकदा बेअरिंग बिघाड झाला."],
    "ai.scopeL3": ["Line 3 · last 2 years", "Line 3 · पिछले 2 साल", "Line 3 · गेली 2 वर्षे"],
    "ai.scopePlant": ["plant-wide · recorded history", "पूरा प्लांट · दर्ज इतिहास", "संपूर्ण प्लांट · नोंदवलेला इतिहास"],
    "ai.bearingDt": ["Total bearing downtime", "बेयरिंग से कुल डाउनटाइम", "बेअरिंगमुळे एकूण डाउनटाइम"],
    "ai.bearingEvents": ["Bearing failure events", "बेयरिंग खराबी की घटनाएँ", "बेअरिंग बिघाड घटना"],
    "ai.eventsHrs": ["{n} events, {h} hrs", "{n} घटनाएँ, {h} घंटे", "{n} घटना, {h} तास"],
    "ai.partSummary": ["<b>{p}</b> appears in <b>{m} machines</b> with <b>{n} recorded replacements</b>. Last used {d}.", "<b>{p}</b> <b>{m} मशीनों</b> में लगा है — <b>{n} बार बदला गया</b>। आख़िरी बार {d} को।", "<b>{p}</b> <b>{m} मशीन्समध्ये</b> आहे — <b>{n} वेळा बदलले</b>. शेवटी {d} रोजी."],
    "ai.concentration": ["Concentration", "केंद्रित उपयोग", "एकवटलेला वापर"],
    "ai.share": ["{line} share", "{line} हिस्सा", "{line} वाटा"],
    "ai.ofUses": ["{a} of {b} recorded uses", "{b} में से {a} उपयोग", "{b} पैकी {a} वापर"],
    "ai.replacementsN": ["{n} replacements", "{n} बार बदला", "{n} वेळा बदलले"],
    "ai.machinesLbl": ["Machines", "मशीनें", "मशीन्स"],
    "ai.highest": ["<b>{name}</b> has the highest recorded downtime: <b>{h} hrs</b> across {n} breakdowns.", "सबसे ज़्यादा डाउनटाइम <b>{name}</b> का है: {n} ब्रेकडाउन में <b>{h} घंटे</b>।", "सर्वाधिक डाउनटाइम <b>{name}</b> चा आहे: {n} ब्रेकडाउनमध्ये <b>{h} तास</b>."],
    "ai.hrsBrk": ["{h} hrs ({n} breakdowns)", "{h} घंटे ({n} ब्रेकडाउन)", "{h} तास ({n} ब्रेकडाउन)"],
    "ai.searchSummary": ["Found <b>{n} records</b> related to “{q}” — including shorthand and Hinglish variants (brng, BRG, bearing gaya).", "“{q}” से जुड़े <b>{n} रिकॉर्ड</b> मिले — शॉर्टहैंड और हिंग्लिश रूप (brng, BRG, bearing gaya) भी शामिल।", "“{q}” शी संबंधित <b>{n} रेकॉर्ड</b> सापडले — शॉर्टहँड आणि हिंग्लिश रूपांसह (brng, BRG, bearing gaya)."],
    "ai.similarIntro": ["Records most similar to the latest failure on <b>Line 3 Conveyor Motor</b> (bearing noise):", "<b>Line 3 कन्वेयर मोटर</b> की ताज़ा खराबी (बेयरिंग आवाज़) से मिलते-जुलते रिकॉर्ड:", "<b>Line 3 कन्व्हेयर मोटर</b> च्या ताज्या बिघाडाशी (बेअरिंग आवाज) जुळणारे रेकॉर्ड:"],
    "why.sameMode": ["Same failure mode", "वही खराबी", "तोच बिघाड"],
    "why.sameType": ["Same machine type", "वही मशीन प्रकार", "तोच मशीन प्रकार"],
    "why.sharedPart": ["Shared part", "एक ही पार्ट", "समान पार्ट"],
    "why.semantic": ["Semantic similarity (shorthand)", "शॉर्टहैंड मिलान", "शॉर्टहँड जुळणी"],

    /* ---- failure mode display names ---- */
    "mode.Bearing": ["Bearing", "बेयरिंग", "बेअरिंग"],
    "mode.Coupling": ["Coupling", "कपलिंग", "कपलिंग"],
    "mode.VFD": ["VFD", "VFD", "VFD"],
    "mode.Alignment": ["Alignment", "अलाइनमेंट", "अलाइनमेंट"],
    "mode.Overheating": ["Overheating", "गरम होना", "जास्त तापणे"],
    "mode.Electrical trip": ["Electrical trip", "बिजली ट्रिप", "वीज ट्रिप"],
    "mode.Sensor": ["Sensor", "सेंसर", "सेन्सर"],
    "mode.Belt": ["Belt", "बेल्ट", "बेल्ट"],
    "mode.Leakage": ["Leakage", "लीकेज", "गळती"],
    "mode.Lubrication": ["Lubrication", "ग्रीसिंग", "वंगण"],
    "mode.Preventive": ["Preventive", "PM (निवारक)", "PM (प्रतिबंधक)"],
    "mode.Inspection": ["Inspection", "निरीक्षण", "तपासणी"],
    "mode.Other": ["Other", "अन्य", "इतर"],

    /* ---- upload ---- */
    "up.title": ["Import Maintenance History", "मेंटेनेंस इतिहास इम्पोर्ट करें", "मेंटेनन्स इतिहास इम्पोर्ट करा"],
    "up.sub": ["Bring your existing maintenance records. No sensors. No SAP changes required.", "अपने मौजूदा रिकॉर्ड लाएँ। न कोई सेंसर, न SAP में बदलाव।", "तुमचे सध्याचे रेकॉर्ड आणा. सेन्सर नाही, SAP बदल नाही."],
    "up.dropTitle": ["Drag & drop files here", "फ़ाइलें यहाँ खींचकर छोड़ें", "फाईल्स इथे ड्रॅग करून सोडा"],
    "up.dropSub": ["or click to browse. In this demo, any drop loads the sample file.", "या क्लिक करके चुनें। डेमो में कोई भी फ़ाइल छोड़ने पर सैंपल फ़ाइल लोड होती है।", "किंवा क्लिक करून निवडा. डेमोमध्ये कोणतीही फाईल टाकल्यास सॅम्पल फाईल लोड होते."],
    "up.process": ["Process file", "फ़ाइल प्रोसेस करें", "फाईल प्रोसेस करा"],
    "up.reRun": ["Re-run import demo", "इम्पोर्ट डेमो फिर चलाएँ", "इम्पोर्ट डेमो पुन्हा चालवा"],
    "up.pipeline": ["Processing pipeline", "प्रोसेसिंग पाइपलाइन", "प्रोसेसिंग पाइपलाइन"],
    "up.simulated": ["simulated for this demo", "डेमो के लिए सिम्युलेटेड", "डेमोसाठी सिम्युलेटेड"],
    "up.complete": ["Import complete", "इम्पोर्ट पूरा", "इम्पोर्ट पूर्ण"],
    "up.detected": ["records detected", "रिकॉर्ड मिले", "रेकॉर्ड आढळले"],
    "up.usable": ["usable", "उपयोगी", "वापरण्याजोगे"],
    "up.skipped": ["skipped (empty/duplicate)", "छोड़े गए (खाली/डुप्लीकेट)", "वगळले (रिकामे/डुप्लिकेट)"],
    "up.review": ["require review", "जाँच ज़रूरी", "तपासणी आवश्यक"],
    "up.reads": ["What LogSense reads", "LogSense क्या-क्या पढ़ता है", "LogSense काय काय वाचते"],
    "up.readsBody": ["Excel breakdown logs, CMMS/SAP exports, PDF reports, scanned handwritten registers, and technician shorthand in Hindi/English.", "Excel ब्रेकडाउन लॉग, CMMS/SAP एक्सपोर्ट, PDF रिपोर्ट, स्कैन किए हाथ से लिखे रजिस्टर, और हिंदी/अंग्रेज़ी में तकनीशियन शॉर्टहैंड।", "Excel ब्रेकडाउन लॉग, CMMS/SAP एक्सपोर्ट, PDF रिपोर्ट, स्कॅन केलेली हस्तलिखित रजिस्टर, आणि हिंदी/इंग्रजीतील तंत्रज्ञ शॉर्टहँड."],
    "step.Upload": ["Upload", "अपलोड", "अपलोड"],
    "step.Parse": ["Parse", "पार्स", "पार्स"],
    "step.Clean": ["Clean", "सफ़ाई", "सफाई"],
    "step.Normalize": ["Normalize", "नॉर्मलाइज़", "नॉर्मलाइझ"],
    "step.Resolve machines": ["Resolve machines", "मशीन पहचान", "मशीन ओळख"],
    "step.Extract failure modes": ["Extract failure modes", "खराबी प्रकार निकालना", "बिघाड प्रकार काढणे"],
    "step.Validation": ["Validation", "जाँच", "तपासणी"],
    "step.Index": ["Index", "इंडेक्स", "इंडेक्स"],

    /* ---- validation ---- */
    "vq.title": ["AI Validation Queue", "AI जाँच कतार", "AI तपासणी रांग"],
    "vq.sub": ["Review records where AI confidence is below the automatic approval threshold. Approved records enter machine history, search and statistics.", "जिन रिकॉर्ड में AI का भरोसा कम है, उन्हें यहाँ जाँचें। मंज़ूर रिकॉर्ड मशीन इतिहास, खोज और आँकड़ों में जुड़ते हैं।", "AI चा विश्वास कमी असलेले रेकॉर्ड इथे तपासा. मंजूर रेकॉर्ड मशीन इतिहास, शोध आणि आकडेवारीत जोडले जातात."],
    "vq.original": ["Original record", "मूल रिकॉर्ड", "मूळ रेकॉर्ड"],
    "vq.extracted": ["AI-extracted record", "AI ने निकाला रिकॉर्ड", "AI ने काढलेले रेकॉर्ड"],
    "vq.pendingCount": ["{n} records pending review", "{n} रिकॉर्ड जाँच के लिए बाकी", "{n} रेकॉर्ड तपासणीसाठी बाकी"],
    "vq.aliasHead": ["Grouped machine alias detected", "एक जैसे मशीन नाम मिले", "सारखी मशीन नावे आढळली"],
    "vq.aliasBody": ["<b>{n} records</b> use the machine name {alias} — LogSense suggests they refer to <b>{target}</b>.", "<b>{n} रिकॉर्ड</b> में मशीन का नाम {alias} लिखा है — LogSense के अनुसार यह <b>{target}</b> है।", "<b>{n} रेकॉर्ड</b> मध्ये मशीनचे नाव {alias} आहे — LogSense नुसार ती <b>{target}</b> आहे."],
    "vq.mapBtn": ["Map to {target}", "{target} से जोड़ें", "{target} शी जोडा"],
    "vq.mappedHead": ["Machine alias updated", "मशीन का नाम जोड़ा गया", "मशीनचे नाव जोडले"],
    "vq.mappedBody": ["{n} records using {alias} are now mapped to <b>{target}</b> and included in its history, search and statistics.", "{alias} वाले {n} रिकॉर्ड अब <b>{target}</b> से जुड़ गए हैं — इतिहास, खोज और आँकड़ों में शामिल।", "{alias} असलेले {n} रेकॉर्ड आता <b>{target}</b> शी जोडले — इतिहास, शोध आणि आकडेवारीत समाविष्ट."],
    "vq.humanHead": ["Human validation is part of the product", "इंसानी जाँच प्रोडक्ट का हिस्सा है", "मानवी तपासणी प्रॉडक्टचा भाग आहे"],
    "vq.humanBody": ["Low-confidence extractions are never silently trusted — a reviewer approves, edits or rejects them before they join the searchable history.", "कम भरोसे वाले रिकॉर्ड पर आँख बंद करके भरोसा नहीं किया जाता — जाँचकर्ता उन्हें मंज़ूर, बदलता या अस्वीकार करता है, तभी वे खोज में जुड़ते हैं।", "कमी विश्वासाच्या रेकॉर्डवर आंधळा विश्वास ठेवला जात नाही — तपासणारा ते मंजूर, बदल किंवा नाकारतो, त्यानंतरच ते शोधात जोडले जातात."],
    "vq.approved": ["Approved — indexed into machine history", "मंज़ूर — मशीन इतिहास में जुड़ा", "मंजूर — मशीन इतिहासात जोडले"],
    "vq.rejected": ["Rejected — excluded from the index", "अस्वीकृत — इंडेक्स से बाहर", "नाकारले — इंडेक्समधून वगळले"],

    /* ---- patterns / parts ---- */
    "pat.title": ["Failure Patterns", "खराबी के पैटर्न", "बिघाडाचे पॅटर्न"],
    "pat.sub": ["Patterns detected from the recorded history, with evidence counts. Hypotheses stay hypotheses — nothing here is a confirmed root cause.", "रिकॉर्ड इतिहास से मिले पैटर्न, सबूतों की गिनती के साथ। अनुमान अनुमान ही रहता है — यहाँ कुछ भी पक्का कारण नहीं है।", "रेकॉर्ड इतिहासातून आढळलेले पॅटर्न, पुराव्यांच्या संख्येसह. अंदाज अंदाजच राहतो — इथे काहीही निश्चित कारण नाही."],
    "parts.title": ["Spare Parts Intelligence", "स्पेयर पार्ट्स इंटेलिजेंस", "स्पेअर पार्ट्स इंटेलिजन्स"],
    "parts.sub": ["Part consumption reconstructed from maintenance records — which parts, on which machines, how often.", "मेंटेनेंस रिकॉर्ड से बनी पार्ट खपत — कौन-सा पार्ट, किस मशीन पर, कितनी बार।", "मेंटेनन्स रेकॉर्डमधून काढलेला पार्ट वापर — कोणता पार्ट, कोणत्या मशीनवर, किती वेळा."],
    "trend.High": ["High", "ज़्यादा", "जास्त"],
    "trend.Medium": ["Medium", "मध्यम", "मध्यम"],
    "trend.Stable": ["Stable", "स्थिर", "स्थिर"],

    /* ---- whatsapp ---- */
    "wa.title": ["WhatsApp Entry Agent", "व्हाट्सऐप एंट्री एजेंट", "व्हॉट्सॲप एंट्री एजंट"],
    "wa.sub": ["Technicians report breakdowns the way they already talk — the agent structures it, asks for what’s missing, and saves a traceable record. Simulated conversation, no real WhatsApp API.", "तकनीशियन अपनी बोलचाल की भाषा में खराबी बताते हैं — एजेंट उसे व्यवस्थित करता है, जो जानकारी कम हो वह पूछता है, और रिकॉर्ड सेव करता है। यह सिम्युलेटेड बातचीत है, असली WhatsApp API नहीं।", "तंत्रज्ञ त्यांच्या नेहमीच्या भाषेत बिघाड सांगतात — एजंट ते नीट मांडतो, कमी माहिती विचारतो आणि रेकॉर्ड सेव्ह करतो. ही सिम्युलेटेड बातचीत आहे, खरे WhatsApp API नाही."],
    "wa.how": ["How this flow works", "यह कैसे चलता है", "हे कसे चालते"],
    "wa.step1": ["Technician reports the breakdown in plain Hinglish", "तकनीशियन आम बोलचाल में खराबी बताता है", "तंत्रज्ञ नेहमीच्या भाषेत बिघाड सांगतो"],
    "wa.step2": ["Agent extracts machine, issue, action — and asks for what is missing", "एजेंट मशीन, समस्या, काम समझता है — और कमी की जानकारी पूछता है", "एजंट मशीन, समस्या, कृती समजून घेतो — आणि कमी माहिती विचारतो"],
    "wa.step3": ["Technician answers; agent asks for one confirmation", "तकनीशियन जवाब देता है; एजेंट एक पुष्टि माँगता है", "तंत्रज्ञ उत्तर देतो; एजंट एक पुष्टी मागतो"],
    "wa.step4": ["Record saved into machine history with full traceability", "रिकॉर्ड मशीन इतिहास में सेव — पूरे सबूत के साथ", "रेकॉर्ड मशीन इतिहासात सेव्ह — संपूर्ण पुराव्यासह"],
    "wa.why": ["Why it matters", "यह क्यों ज़रूरी है", "हे का महत्त्वाचे"],
    "wa.whyBody": ["No new forms, no app to learn. Technician knowledge — “Yadav sir bolte hai shaft me runout hai” — stops living only in people’s heads.", "न नया फॉर्म, न नई ऐप सीखनी। तकनीशियन का ज्ञान — “Yadav sir bolte hai shaft me runout hai” — सिर्फ़ लोगों के दिमाग़ में नहीं रहता।", "नवीन फॉर्म नाही, नवीन ॲप शिकायचे नाही. तंत्रज्ञाचे ज्ञान — “Yadav sir bolte hai shaft me runout hai” — फक्त लोकांच्या डोक्यात राहत नाही."],
    "wa.tryIt": ["Try it", "आज़माएँ", "करून पहा"],
    "wa.tryBody": ["Tap the suggested message under the chat (or type your own) to start the conversation.", "चैट के नीचे सुझाया गया मैसेज दबाएँ (या अपना लिखें) और बातचीत शुरू करें।", "चॅटखालील सुचवलेला मेसेज दाबा (किंवा स्वतः लिहा) आणि संवाद सुरू करा."],
    "wa.savedHead": ["Record #2048 saved", "रिकॉर्ड #2048 सेव हुआ", "रेकॉर्ड #2048 सेव्ह झाले"],
    "wa.savedBody": ["Open the machine to see the new timeline entry and the recurrence alert.", "मशीन खोलें — नई टाइमलाइन एंट्री और अलर्ट देखें।", "मशीन उघडा — नवीन टाइमलाइन नोंद आणि अलर्ट पहा."],
    "wa.greeting": ["Namaste Ramesh 🙏 Report a breakdown in Hindi or English — machine, kya hua, kya kiya.", "नमस्ते रमेश 🙏 खराबी हिंदी या अंग्रेज़ी में बताइए — मशीन, क्या हुआ, क्या किया।", "नमस्कार रमेश 🙏 बिघाड मराठी, हिंदी किंवा इंग्रजीत सांगा — मशीन, काय झाले, काय केले."],
    "wa.understood": ["I understood:\n\n<b>Machine:</b> Line 3 Conveyor Motor\n<b>Issue:</b> Bearing failure\n<b>Action:</b> Bearing replaced\n<b>Alignment:</b> Checked\n<b>Status:</b> Running\n<b>Downtime:</b> Not provided\n\nHow long was the machine down?", "मैंने समझा:\n\n<b>मशीन:</b> Line 3 कन्वेयर मोटर\n<b>समस्या:</b> बेयरिंग खराबी\n<b>काम:</b> बेयरिंग बदली\n<b>अलाइनमेंट:</b> जाँची गई\n<b>स्थिति:</b> चालू\n<b>डाउनटाइम:</b> नहीं बताया\n\nमशीन कितनी देर बंद थी?", "मला समजले:\n\n<b>मशीन:</b> Line 3 कन्व्हेयर मोटर\n<b>समस्या:</b> बेअरिंग बिघाड\n<b>कृती:</b> बेअरिंग बदलले\n<b>अलाइनमेंट:</b> तपासले\n<b>स्थिती:</b> चालू\n<b>डाउनटाइम:</b> सांगितले नाही\n\nमशीन किती वेळ बंद होती?"],
    "wa.confirmMsg": ["Please confirm:\n\n<b>Line 3 Conveyor Motor</b>\nBearing failure\nBearing replaced\nAlignment checked\nDowntime: <b>2 hours</b>", "कृपया पुष्टि करें:\n\n<b>Line 3 कन्वेयर मोटर</b>\nबेयरिंग खराबी\nबेयरिंग बदली\nअलाइनमेंट जाँची\nडाउनटाइम: <b>2 घंटे</b>", "कृपया निश्चित करा:\n\n<b>Line 3 कन्व्हेयर मोटर</b>\nबेअरिंग बिघाड\nबेअरिंग बदलले\nअलाइनमेंट तपासले\nडाउनटाइम: <b>2 तास</b>"],
    "wa.savedMsg": ["✅ Maintenance record <b>#2048</b> created successfully.\n\nLine 3 Conveyor Motor · Bearing replaced · 2.0 hrs downtime\nSource: WhatsApp · Technician: Ramesh", "✅ मेंटेनेंस रिकॉर्ड <b>#2048</b> बन गया।\n\nLine 3 कन्वेयर मोटर · बेयरिंग बदली · 2.0 घंटे डाउनटाइम\nस्रोत: WhatsApp · तकनीशियन: रमेश", "✅ मेंटेनन्स रेकॉर्ड <b>#2048</b> तयार झाले.\n\nLine 3 कन्व्हेयर मोटर · बेअरिंग बदलले · 2.0 तास डाउनटाइम\nस्रोत: WhatsApp · तंत्रज्ञ: रमेश"],
    "wa.fifthNote": ["⚠️ Note for the maintenance team: this is the <b>5th bearing replacement</b> on this motor since Nov 2025. LogSense has flagged the recurrence for <b>engineering review</b>.", "⚠️ मेंटेनेंस टीम के लिए: नवंबर 2025 से इस मोटर पर यह <b>5वीं बेयरिंग बदली</b> है। LogSense ने इसे <b>इंजीनियरिंग जाँच</b> के लिए फ्लैग किया है।", "⚠️ मेंटेनन्स टीमसाठी: नोव्हेंबर 2025 पासून या मोटरवरील हे <b>5वे बेअरिंग बदल</b> आहे. LogSense ने हे <b>इंजिनिअरिंग तपासणीसाठी</b> फ्लॅग केले आहे."],
    "wa.viewInHistory": ["View in machine history", "मशीन इतिहास में देखें", "मशीन इतिहासात पहा"],
    "wa.openHistory": ["Open machine history", "मशीन इतिहास खोलें", "मशीन इतिहास उघडा"],
    "wa.useConfirm": ["Please use the <b>Confirm</b> button above, or type what should change.", "ऊपर <b>पुष्टि करें</b> बटन दबाएँ, या जो बदलना है वह लिखें।", "वरचे <b>निश्चित करा</b> बटण दाबा, किंवा काय बदलायचे ते लिहा."],
    "wa.alreadySaved": ["Record #2048 is already saved. Send a new breakdown report anytime — I'm listening. 👍", "रिकॉर्ड #2048 पहले ही सेव है। नई खराबी कभी भी भेजिए — मैं सुन रहा हूँ। 👍", "रेकॉर्ड #2048 आधीच सेव्ह आहे. नवीन बिघाड कधीही पाठवा — मी ऐकतोय. 👍"],
    "wa.editHint": ["No problem — reply with the field to change, e.g. <b>“downtime 3 ghante”</b>. (In this demo, press Confirm to continue the story.)", "कोई बात नहीं — जो बदलना है वह लिखें, जैसे <b>“downtime 3 ghante”</b>। (डेमो में आगे बढ़ने के लिए पुष्टि करें दबाएँ।)", "हरकत नाही — काय बदलायचे ते लिहा, उदा. <b>“downtime 3 ghante”</b>. (डेमोमध्ये पुढे जाण्यासाठी निश्चित करा दाबा.)"],
    "wa.simNote": ["Messages are simulated — no real WhatsApp connection. Today:", "मैसेज सिम्युलेटेड हैं — असली WhatsApp कनेक्शन नहीं। आज:", "मेसेज सिम्युलेटेड आहेत — खरे WhatsApp कनेक्शन नाही. आज:"],
    "wa.typePh": ["Type a message", "मैसेज लिखें", "मेसेज लिहा"],
    "wa.online": ["online", "ऑनलाइन", "ऑनलाइन"],

    /* ---- closing slide ---- */
    "close.h1": ["Your Plant’s Memory,<br>Searchable.", "आपके प्लांट की याददाश्त,<br>अब खोजने लायक़।", "तुमच्या प्लांटची स्मृती,<br>आता शोधण्याजोगी."],
    "close.no1": ["No sensors", "कोई सेंसर नहीं", "सेन्सर नाहीत"],
    "close.no2": ["No SAP migration", "कोई SAP माइग्रेशन नहीं", "SAP मायग्रेशन नाही"],
    "close.no3": ["No additional maintenance forms", "कोई नया फॉर्म नहीं", "नवीन फॉर्म नाहीत"],
    "close.line": ["Years of existing maintenance history → <strong>searchable intelligence</strong>, live in <strong>4 weeks</strong>.", "सालों का मौजूदा मेंटेनेंस इतिहास → <strong>खोजने लायक़ इंटेलिजेंस</strong>, सिर्फ़ <strong>4 हफ़्तों</strong> में।", "वर्षानुवर्षांचा मेंटेनन्स इतिहास → <strong>शोधण्याजोगी इंटेलिजन्स</strong>, फक्त <strong>4 आठवड्यांत</strong>."],

    /* ---- misc page titles ---- */
    "users.title": ["Users & Roles", "उपयोगकर्ता और भूमिकाएँ", "वापरकर्ते आणि भूमिका"],
    "settings.title": ["Settings", "सेटिंग्स", "सेटिंग्ज"],
    "how.title": ["How LogSense Works", "LogSense कैसे काम करता है", "LogSense कसे काम करते"],
  };

  /* Localized assistant suggestion chips (also understood by the intent router) */
  const SUGGESTIONS = {
    en: [
      "Line 3 ke conveyor motor pe pichle 2 saal mein kya kya hua?",
      "Which machines have repeated bearing failures?",
      "Total downtime bearing failures Line 3 last 2 years",
      "6205 bearing kahan kahan lagi hai?",
      "Which machine has the highest downtime?",
      "bearing noise conveyor",
    ],
    hi: [
      "Line 3 के कन्वेयर मोटर पर पिछले 2 साल में क्या-क्या हुआ?",
      "किन मशीनों में बार-बार बेयरिंग खराब हुई?",
      "Line 3 पर बेयरिंग खराबी का कुल डाउनटाइम कितना?",
      "6205 बेयरिंग कहाँ-कहाँ लगी है?",
      "सबसे ज़्यादा डाउनटाइम किस मशीन का है?",
      "bearing noise conveyor",
    ],
    mr: [
      "Line 3 च्या कन्व्हेयर मोटरवर गेल्या 2 वर्षांत काय काय झाले?",
      "कोणत्या मशीनमध्ये वारंवार बेअरिंग खराब झाले?",
      "Line 3 वर बेअरिंग बिघाडाचा एकूण डाउनटाइम किती?",
      "6205 बेअरिंग कुठे कुठे लागले आहे?",
      "सर्वात जास्त डाउनटाइम कोणत्या मशीनचा?",
      "bearing noise conveyor",
    ],
  };

  LS.i18n = {
    get lang() { return lang; },
    langs: [
      { code: "en", label: "EN" },
      { code: "hi", label: "हिंदी" },
      { code: "mr", label: "मराठी" },
    ],
    suggestions: () => SUGGESTIONS[lang] || SUGGESTIONS.en,
  };

  LS.t = function (key) {
    const e = dict[key];
    if (!e) return key;
    return e[ORDER[lang]] || e[0];
  };

  LS.tf = function (key, vars) {
    let s = LS.t(key);
    Object.entries(vars || {}).forEach(([k, v]) => {
      s = s.split("{" + k + "}").join(String(v));
    });
    return s;
  };

  /* Failure-mode display name (data keeps canonical English internally) */
  LS.tMode = function (mode) {
    const e = dict["mode." + mode];
    return e ? (e[ORDER[lang]] || e[0]) : mode;
  };

  LS.setLang = function (code) {
    if (!(code in ORDER)) return;
    lang = code;
    try { sessionStorage.setItem(LANG_KEY, code); } catch (e) { /* noop */ }
    document.documentElement.lang = code === "en" ? "en" : code;
    if (LS.applyLang) LS.applyLang();
  };

  document.documentElement.lang = lang === "en" ? "en" : lang;
})();
