spring:
  application:
    name: Store Management System

  profiles:
    active: dev

  jpa:
    open-in-view: false
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  thymeleaf:
    encoding: UTF-8
    mode: HTML

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB

server:
  port: 8080
  error:
    include-message: always
    include-stacktrace: never
